name: Compile, Deploy and Build Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  NODE_VERSION: 20
  APP_NAME: angular-induservice-fl
  BASE_HREF: ./

jobs:
  compile:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular App
        run: npm run build -- --configuration=production --base-href="/"

      - name: Prevent Jekyll processing
        run: touch dist/${{ env.APP_NAME }}/.nojekyll

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    needs: compile
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./dist/${{ env.APP_NAME }}
          clean: true